### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by juliolpiva** [felpin/pokemon-market#1]
After i cloned the repo and used yarn install, I try to run with YARN START, bug get this error:

PS C:\Workspace\SandBox\pokemon-market> yarn start
yarn run v1.3.2
$ node index.js
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\Workspace\SandBox\pokemon-market\index.js:18:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by felpin** [comment]
This happens because it is trying to read the SSL certificate, but it is not being found.

First you have to create a self signed certificate (it tells your machine that the website you are accessing through HTTPS is valid because your machine said so). You can create one in http://www.selfsignedcertificate.com/

So... After creating your self signed certificate, you'll have two files: a CRT file and a KEY file. Save them anywhere (you can save in the root of the project) and when starting the application, make sure that there is an environment variable SSL_CRT with the location of CRT file and another environment variable SSL_KEY with the location of KEY file.
